// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSourceKind } from "./ThreadSourceKind";

/**
 * Scope for read-state and side-summary operations.
 */
export type ThreadReadStateScope = {
/**
 * Optional provider filter; when omitted, defaults to the current provider.
 * When present but empty, includes all providers.
 */
modelProviders?: Array<string> | null,
/**
 * Optional source filter; when omitted or empty, defaults to interactive sources.
 */
sourceKinds?: Array<ThreadSourceKind> | null,
/**
 * Optional archived filter; when true, matches archived threads instead of active threads.
 */
archived?: boolean | null,
/**
 * Optional cwd filter or filters.
 */
cwd?: string | Array<string> | null,
/**
 * Optional substring filter for the extracted thread title or preview.
 */
searchTerm?: string | null,
/**
 * If true, read directly from the state DB without scanning JSONL rollouts to repair metadata.
 */
useStateDbOnly?: boolean, };
