// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadReadStateScope } from "./ThreadReadStateScope";
import type { ThreadSideSummaryEntry } from "./ThreadSideSummaryEntry";

export type ThreadSideSummary = { id: string,
/**
 * Unix timestamp (in seconds) when the summary was created.
 */
createdAt: number,
/**
 * Unix timestamp (in seconds) for the read marker written by the summary action.
 */
readAt: number, scope: ThreadReadStateScope, threadCount: number, unreadCount: number, markdown: string, entries: Array<ThreadSideSummaryEntry>, };
