// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionSource } from "./SessionSource";
import type { ThreadSource } from "./ThreadSource";
import type { ThreadStatus } from "./ThreadStatus";

export type ThreadSideSummaryEntry = { threadId: string, name: string | null, preview: string, summary: string, status: ThreadStatus, source: SessionSource, threadSource: ThreadSource | null,
/**
 * Unix timestamp (in seconds) when the thread was last updated.
 */
updatedAt: number,
/**
 * Whether this thread was unread before the summary action marked it read.
 */
wasUnread: boolean, };
